language: scala

scala:
  - 2.12.7
  
os:
    - linux

before_install: 
    - wget http://user.it.uu.se/~petba168/z3-4.5.0
    - mv z3-4.5.0 z3
    - wget http://user.it.uu.se/~petba168/mathsat.master    
    - mv mathsat.master mathsat
    - chmod u+=x z3
    - chmod u+=x mathsat
    - echo "(exit)" > test.smt2
    - export PATH=$PATH:`pwd`
    - z3 -smt2 test.smt2
    - mathsat test.smt2
